# Generated by Django 5.2.13 on 2026-04-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbandonedCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_snapshot', models.JSONField(blank=True, default=dict)),
                ('is_converted', models.BooleanField(db_index=True, default=False)),
                ('reminder_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent')], db_index=True, default='pending', max_length=20)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=128)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('product_view', 'Product View'), ('add_to_cart', 'Add To Cart'), ('checkout', 'Checkout'), ('order_completed', 'Order Completed')], db_index=True, max_length=30)),
                ('path', models.CharField(blank=True, max_length=300)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='homepage/hero/')),
                ('button_text', models.CharField(blank=True, max_length=120)),
                ('button_link', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='homepage/sections/')),
                ('section_type', models.CharField(choices=[('collection', 'Collection'), ('promotional', 'Promotional'), ('banner', 'Banner')], default='banner', max_length=20)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('button_text', models.CharField(blank=True, max_length=120)),
                ('button_link', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Raaya India', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('footer_text', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
