# Generated by Django 5.2.13 on 2026-04-09 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='abandonedcart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abandoned_cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='orders.order'),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='products.product'),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='herobanner',
            index=models.Index(fields=['is_active', 'updated_at'], name='admin_panel_is_acti_656257_idx'),
        ),
        migrations.AddIndex(
            model_name='homesection',
            index=models.Index(fields=['is_active', 'order', 'section_type'], name='admin_panel_is_acti_ebb88c_idx'),
        ),
        migrations.AddIndex(
            model_name='abandonedcart',
            index=models.Index(fields=['is_converted', 'reminder_status'], name='admin_panel_is_conv_bf57f0_idx'),
        ),
        migrations.AddIndex(
            model_name='abandonedcart',
            index=models.Index(fields=['last_activity'], name='admin_panel_last_ac_8dabe8_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['session_id', 'event_type'], name='admin_panel_session_37f029_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['created_at'], name='admin_panel_created_c3946d_idx'),
        ),
    ]
