# Generated by Django 5.2.13 on 2026-04-09 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('verification_status', models.BooleanField(db_index=True, default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['store_name'],
                'indexes': [models.Index(fields=['store_name'], name='vendors_ven_store_n_ea5b94_idx'), models.Index(fields=['verification_status'], name='vendors_ven_verific_039b78_idx'), models.Index(fields=['is_active'], name='vendors_ven_is_acti_5c8a37_idx')],
            },
        ),
    ]
